################ Splash page #######################
[splash]
label = ""
contentDir = "content/splash"
weight = 1

################ English language ##################
[en]
label = "English"
locale = "en-CA"
contentDir = "content/en"
weight = 2

[fr]
label = "Français"
locale = "fr-CA"
contentDir = "content/fr"
weight = 3
