name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.145.0"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Newsletter Dependencies
        run: |
          cd newsletter
          npm install

      - name: Build Newsletter (Email HTML)
        run: |
          cd newsletter
          npm run build:email

      - name: Build Hugo Site
        run: hugo --minify

      - name: Copy Newsletter HTML to Hugo Public Folder
        run: |
          mkdir -p public/newsletter
          cp newsletter/*.html public/newsletter/
          cp -r newsletter/assets public/newsletter/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
